config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :flights, only: [:index]
  resources :bookings, only: [:index, :new, :create, :show]
  root 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, foreign_key: :from_airport_id, class_name: "Flight"
    has_many :arrival_flights, foreign_key: :to_airport_id, class_name: "Flight"

    def self.details(id)
        airport = Airport.find(id)
        airport_string = "#{airport.city}, #{airport.state} (#{airport.airport_code})"
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :flight 
    has_many :passengers, dependent: :destroy
    accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :to_airport, class_name: "Airport"
    belongs_to :from_airport, class_name: "Airport"
    has_many :bookings
    has_many :passengers, through: :bookings

    scope :generate_dates, -> { distinct.order("date(departure_time)").pluck("date(departure_time)") }
    scope :find_flights, -> (from_airport, to_airport, date){where("from_airport_id = ? AND to_airport_id = ? AND date(departure_time) = ?", from_airport, to_airport, date).order(:departure_time)}
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    before_action :set_flight, only: [:new]

    def index
        @search_submit = false
        @email = params["email"]
        if @email
            @search_submit = true
            @bookings = Booking.joins(:passengers).where("email=?", params["email"])
        end
    end

    def new
        @booking = Booking.new
        @passengers = params["passengers"].to_i
        @passengers.times do
            @booking.passengers.build
        end
    end

    def create
        @booking = Booking.new(booking_params)
        
        puts @booking.id
        respond_to do |format|
            if @booking.save
                @booking.passengers.each do |passenger|
                    PassengerMailer.with(booking: @booking, passenger: passenger).confirmation_email.deliver_now!
                end
                format.html { redirect_to booking_path(@booking), notice: 'Your flight booking has been successfully submitted' }
            else
                @flight = Flight.find(params[:booking][:flight_id])
                format.html { render :new, notice: :unprocessable_entity }
            end
        end
    end

    def show
        @booking = Booking.find(params[:id])
        @flight = Flight.find(@booking.flight_id)        
    end

    private 
    def booking_params
        params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
    end

    def set_flight
        @flight = Flight.find(params["flight_id"])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    before_action :set_search_submit 
    def index
        if params['from_airport_id']
            @search_submit = true
            @params = params
            @found_flights = Flight.find_flights(params['from_airport_id'], params['to_airport_id'], params['date'])
            @passengers = params['passengers']
        end
        @from_airport = Airport.all.map { |a| ["#{a.city}, #{a.state} (#{a.airport_code})", a.id] }
        @to_airport = Airport.all.map { |a| ["#{a.city}, #{a.state} (#{a.airport_code})", a.id] }
        @departure_times = Flight.generate_dates.map { |d| [d.strftime("%m-%d-%Y"), d] }
    end


    private
    def set_search_submit
        @search_submit = false
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="columns">
    <div class="column is-8 is-offset-2">
        <div class="mb-5">
            <div class="m-5">
                <h3 class="is-size-4 has-text-weight-bold">Search For Bookings</h3>
            </div>
            
            <%= form_with url: bookings_path, method: :get do |f| %>
                <div class="actions">
                    <div class="field is-horizontal">
                        <div class="field-label has-text-left mr-0 is-align-self-center">
                            <%= f.label 'Enter Email:', class: 'label' %>
                        </div>
                        <div class="field-body is-flow-root">
                            <div class="field is-narrow">
                                <div class="control">
                                    <%= f.email_field :email, class: 'input' %>
                                </div>
                            </div>
                        </div>
                        <%= f.submit 'Search', class: 'button bordered ml-2' %>
                    </div>
                </div>
            <% end %>
        </div>

        <div>
            <% if @search_submit == true %>
                <h3 class="is-size-5 has-text-weight-bold">
                    Showing Bookings For Email: <%= @email %>
                </h3>
                <% if !@bookings.empty? %>
                    <table class="table m-3 is-fullwidth is-hoverable">
                        <thead>
                            <tr>
                                <th>Booking ID</th>
                                <th>Flight Path</th>
                                <th>Flight Date</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @bookings.each do |booking| %>
                                <% flight = Flight.find(booking.flight_id) %>
                                <tr>
                                    <th><%= booking.id %></th>
                                    <th><%= Airport.details(flight.from_airport_id) + "->" + Airport.details(flight.to_airport_id) %></th>
                                    <th><%= flight.departure_time.strftime('%a, %b %d, %Y') %></th>
                                    <th><%= link_to 'Open Booking', booking_path(booking.id), class: 'button' %></th>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/bookings/new.html.erb
<%= form_with(model: @booking, local: true) do |f| %>
    <% if @booking.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
            <% @booking.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>


    <%= f.hidden_field :flight_id, value: @flight.id %>
    <div class="columns m-6">
        <div class="column is-4 is-offset-1" id="flight_details">
            <div class="box has-text-left">
                <h3 class="is-size-4 has-text-weight-bold">Booking Flight For:</h3>
                <div class="m-3"> 
                    <p>
                        <strong>Flight:</strong>
                        <%= @flight.id %>
                    </p>
                    <p>
                        <strong>From: </strong>
                        <%= Airport.details(@flight.from_airport_id) %>
                    </p>
                    <p>
                        <strong>To: </strong>
                        <%= Airport.details(@flight.to_airport_id) %>
                    </p>
                    <p>
                        <strong>Departing At: </strong>
                        <%= @flight.departure_time.strftime('%a, %b %d, %Y at %l:%M %p') %>
                    </p>
                    <p>
                        <strong>Flight Time: </strong>
                        <%= Time.at(@flight.duration.to_i).utc.strftime("%k hr %M min") %>
                    </p>
                </div>
            </div>
        </div>

        <div class="column is-5 box m-3" id="passenger_form">
            <h5 class="is-size-5 has-text-left"><strong>Please Enter Passenger Information</strong></h5>
            <% i = 0 %>
                <%= f.fields_for :passengers do |passenger_form| %>
                    <h6 class="is-size-6 has-text-left m-2"><strong>Passenger <%=  i+=1 if i != @passengers %></strong></h6>
                    <div class="field is-horizontal">
                        <div class="field-label is-align-self-center has-text-weight-semibold">
                            Name: 
                        </div>
                        <div class="field-body">
                            <%= passenger_form.text_field :name, required: true, class: 'input' %>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label is-align-self-center has-text-weight-semibold">
                            Email: 
                        </div>
                        <div class="field-body">
                            <%= passenger_form.text_field :email, required:true, class: 'input' %>
                        </div>
                    </div>
                <% end %>
            <%= f.submit 'Confirm Booking', class: "button" %>
        </div>
    </div>
<% end %>

app/views/bookings/show.html.erb
<div class="columns m-6">
    <div class="column is-6 is-offset-3 box">
        <h3 class="is-size-3"> Booking Summary </h3>
        <br />
        <div class="is-size-6">
            <p class="mb-2">
                <strong>Flight: </strong><%= @flight.id %> 
            </p>
            <p class="mb-2">
                <strong>From: </strong><span class="mr-3"><%= Airport.details(@flight.from_airport_id) %></span>
                <strong>To: </strong><%= Airport.details(@flight.to_airport_id) %>
            </p>
            <p class="mb-2">
                <strong>Departing At: </strong><%= @flight.departure_time.strftime('%a, %b %d, %Y at %l:%M %p') %>
            </p>
            <p class="mb-2">
                <strong>Flight Time: </strong><%= Time.at(@flight.duration.to_i).utc.strftime("%k hr %M min") %>
            </p>
        </div>
        <br />
        <div class="is-size-6 m-3">
            <h5 class="is-size-4 has-text-weight-semibold">Passengers</h5>
            <% @booking.passengers.each_with_index do |passenger, i| %>
                <p class="m-2">
                    <strong>Passenger <%= i+1 %>: </strong>
                    <%= passenger.name + "(" + passenger.email + ")" %>    
                </p>
            <% end %>
        </div>
    </div>
</div>

app/views/flights/_flight_search_results.html.erb
<% if !@found_flights.empty? %>
    <%= form_with url: new_booking_path, method: :get do |form| %>
        <table class="table m-3 is-fullwidth is-hoverable">
            <thead>
                <tr>
                    <th>Flight</th>
                    <th>Departing From</th>
                    <th>Arriving To</th>
                    <th>Date</th>
                    <th>Takeoff Time</th>
                    <th>Flight Time</th>
                    <th>Select Flight</th>
                </tr>
            </thead>
            <tbody>
                <% @found_flights.each do |flight| %>
                    <tr>
                        <th><%= flight.id %></th>
                        <th><%= Airport.details(flight.from_airport_id) %></th>
                        <th><%= Airport.details(flight.to_airport_id) %></th>
                        <th><%= flight.departure_time.strftime('%a, %b %d, %Y') %></th>
                        <th><%= flight.departure_time.strftime('%l:%M %p') %></th>
                        <th><%= Time.at(flight.duration.to_i).utc.strftime("%k hr %M min") %></th>
                        <th><%= form.radio_button :flight_id, flight.id %></th>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= form.hidden_field :passengers, value: @passengers %>
        <%= form.submit 'Continue to Passenger Details', class: 'button is-white bordered is-rounded'%>
    <% end %>
<% else %>
    <div class="m-6">
        <div class="box">
            <h3 class="is-size-3">No Flights Found</h3>
        </div>
    </div>
<% end %>

app/views/flights/index.html.erb
<div class="columns">
    <div class="column is-10 is-offset-1">
        <div id="flight_search_form" class="mb-5">
            <div class="m-5">
                <h3 class="is-size-3 has-text-weight-bold">Flight Search</h3>
            </div>
            <%= form_with url: root_path, method: :get do |form| %>

                <div class="actions">

                    <div class="field is-horizontal columns">
                        <div class="field-label is-align-self-center">
                            <%= form.label 'From', class: 'label' %>
                        </div>
                        <div class="field-body is-flex-grow-2">
                            <div class="field is-narrow">
                                <div class="control">
                                    <div class="select is-fullwidth">
                                        <%= select_tag(:from_airport_id, options_for_select(@from_airport)) %>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="field-label is-align-self-center">
                            <%= form.label 'To', class: 'label' %>
                        </div>
                        <div class="field-body is-flex-grow-2 mr-6">
                            <div class="field is-narrow">
                                <div class="control">
                                    <div class="select is-fullwidth">
                                        <%= select_tag(:to_airport_id, options_for_select(@to_airport)) %>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="field-label is-align-self-center">
                            <%= form.label 'Passengers', class: 'label' %>
                        </div>
                        <div class="field-body is-flex-grow-1">
                            <div class="field is-narrow">
                                <div class="control">
                                    <div class="select is-fullwidth">
                                        <%= select_tag(:passengers, options_for_select([[1,1],[2,2],[3,3],[4,4]])) %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                        <div class="field-label is-align-self-center">
                            <%= form.label :date, class: 'label' %>
                        </div>
                        <div class="field-body is-flex-grow-2">
                            <div class="field">
                                <div class="control">
                                    <div class="select">
                                        <%= select_tag(:date, options_for_select(@departure_times))%>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <%= form.submit 'Search', class: 'button is-white bordered is-normal is-align-self-center' %>
                    </div>
                    
                </div>
            <% end %>
        </div>

        <div id="flight_search_results" class="pt-6">
            <% if @search_submit == true %>
                <h5 class="is-size-5 has-text-weight-bold">
                    Showing Flights From <%= Airport.details(@params["from_airport_id"]) %> To <%= Airport.details(@params["to_airport_id"]) %> On <%= @params["date"] %>
                </h5>
                <div class="is-inline-block">
                    <% date = Date.parse(params['date']) %>
                    <%= form_with url: root_path, method: :get do |prev_form| %>
                        <%= prev_form.hidden_field :from_airport_id, value: @params['from_airport_id'] %>
                        <%= prev_form.hidden_field :to_airport_id, value: @params['to_airport_id'] %>
                        <%= prev_form.hidden_field :passengers, value: @params['passengers'] %>
                        <%= prev_form.hidden_field :date, value: date.prev_day %>
                        <%= prev_form.submit '<< '+date.prev_day.to_s, class: 'button is-white bordered is-small' %>
                        
                    <% end %>
                </div>
                <div class="is-inline-block">
                    <%= form_with url: root_path, method: :get do |next_form| %>
                        <%= next_form.hidden_field :from_airport_id, value: @params['from_airport_id'] %>
                        <%= next_form.hidden_field :to_airport_id, value: @params['to_airport_id'] %>
                        <%= next_form.hidden_field :passengers, value: @params['passengers'] %>
                        <%= next_form.hidden_field :date, value: date.next_day %>
                        <%= next_form.submit date.next_day.to_s+' >>', class: 'button is-white bordered is-small' %>
                    <% end %>
                </div>
                <%= render 'flight_search_results' %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice centered-text notification notice is-primary" onload="notificationTimeOut()"><%= notice %></p>
    <% end%>
    <% if flash[:alert] %>
      <p class="alert centered-text notification notice is-danger" onload="notificationTimeOut()"><%= alert %></p>
    <% end %>
    
    <section class="hero is-light is-fullheight">
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to "flight_tracker", root_path, class: "navbar-item has-text-weight-bold is-size-5" %>
              <span class="navbar-burger" data-target="navbarMenuHeroB">
                <span></span>
                <span></span>
                <span></span>
              </span>
            </div>
            <div id="navbarMenuHeroB" class="navbar-menu">
              <div class="navbar-end">
                <%= link_to 'Search For Flights', root_path, class: 'navbar-item' %>
                <%= link_to 'Find Flight Bookings', bookings_path, class: 'navbar-item' %>
              </div>
            </div>
          </div>
        </nav>
      </div>

      <div class="hero-body is-align-items-start pt-0">
        <div class="container has-text-centered">
          <%= yield %>
        </div>
      </div>
    </section>
    <%= javascript_pack_tag "index"%>
  </body>
</html>